モジュールによる検索を修正
Make-IT-TSUKUBA/alternative-tsukuba-kdb pull request #103
Opened 2022-03-26 14:16 UTC by inaniwaudon

#96 で報告されていた問題を修正しました。

- ● 春 ◯ 秋 ／ ● A ◯ B ◯ C を選択すると、｢春C／秋A」の科目がマッチしてしまう。

2022-03-26 15:15 UTC, eggplants commented
現在のデプロイ<https://make-it-tsukuba.github.io/alternative-tsukuba-kdb/>で試した限りでは修正されているように見えます。
@HiroKoni 期待された動作でしょうか？

---

@inaniwaudon `fix the bugs`からコミットメッセージをわかりやすくしたい場合は:

```
git commit -m "fix searching bug (#96)" --amend
git push -f
```

とやると、GitHub上でコミットメッセージを見た場合`#96`がissueへのリンクになり、またissueにも修正コミットを作成したことが通知されてより良いです！

2022-03-26 15:33 UTC, HiroKoni commented
ご対応ありがとうございます。
#96 で例示した科目や、`HB36151`などの複雑な科目で確認してみましたが、期待通りの動作をしているように見受けられます。

2022-03-26 15:54 UTC, inaniwaudon commented
> 現在のデプロイhttps://make-it-tsukuba.github.io/alternative-tsukuba-kdb/で試した限りでは修正されているように見えます。 @HiroKoni 期待された動作でしょうか？
> 
> @inaniwaudon `fix the bugs`からコミットメッセージをわかりやすくしたい場合は:
> 
> ```
> git commit -m "fix searching bug (#96)" --amend
> git push -f
> ```
> 
> とやると、GitHub上でコミットメッセージを見た場合`#96`がissueへのリンクになり、またissueにも修正コミットを作成したことが通知されてより良いです！

なるほど、ありがとうございます（確かにコミットが汚かったですね……すみません）対応しました！

2022-03-26 23:42 UTC, frodo821 requested changes
確認お願いします

2022-03-26 23:42 UTC, frodo821 commented on src/main.ts
>      let seasonModule = dom.selectModule?.options[dom.selectModule.selectedIndex].value as string;
型が違います。`string | undefined` が正しいです。今回の差分ではないですが、一応。

2022-03-26 23:42 UTC, frodo821 commented on src/main.ts
> +      season = seasonModule.slice(0, 1) as NormalSeasons;
asは可能な限り使わず、タイプガードを利用してください。

2022-03-26 23:42 UTC, frodo821 commented on src/subject/search.ts
> +  }
最初の式をelseに入れるべき

2022-03-30 08:00 UTC, inaniwaudon commented on src/subject/search.ts
> +  }
> 確認お願いします

対応しました  再度確認お願いします

2022-03-30 08:00 UTC, inaniwaudon commented
> 確認お願いします

対応しました。再度確認お願いします

2022-06-04 20:03 UTC, merged