検索要件をまとめてクリアできるようにする
Make-IT-TSUKUBA/alternative-tsukuba-kdb pull request #23
Opened 2021-05-11 05:49 UTC by Mimori256

検索条件をクリアで、req-Bとreq-Cの選択が削除されないので削除されるようにしました。また、CSVファイルを生成するときのfor文でvarが省略されていたので、追記しておきました。

2021-05-11 06:11 UTC, frodo821 requested changes

2021-05-11 06:11 UTC, frodo821 commented
@Mimori256 確認お願いします

2021-05-11 11:26 UTC, frodo821 commented
@Mimori256 
> @frodo821 ならmakeCSVの他のvarもletやconstで置き換えたほうが良いと思ったのですがどうでしょうか?

そこはリファクタリング中なのであとで書き換えます。

2021-05-11 14:42 UTC, Mimori256 commented
修正しました。以後気をつけます

2021-05-12 02:56 UTC, frodo821 approved these changes
LGTM

2021-05-12 02:56 UTC, merged

2021-05-12 02:56 UTC, frodo821 commented
@Mimori256 マージしました！